version: '2.3'

services:
  mysql:
    restart: always
    image: mysql:5.7
    container_name: mysql
    ports:
      - "3307:3306"
    volumes:
      - ./store/:/var/lib/mysql
    mem_limit: 512m
    networks:
      - mysqlnetwork
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=person
  redis-server:
    restart: always
    image: redis:4.0
    container_name: redis-server
    command: /bin/bash -c 'redis-server --appendonly yes'
    sysctls:
      - net.core.somaxconn=65535
    ports:
      - "6380:6379"
    volumes:
      - ./redis:/data
    mem_limit: 96m
    networks:
      - mysqlnetwork
  app:
        container_name: 
         spring-demo-app
        depends_on:
         - mysql
        build: 
         context: .
        restart: always
        links:
         - mysql
        ports:
         - 8080:8080
volumes:
  mysql:
    driver: local
  redis:
    driver: local
networks:
  mysqlnetwork:
    driver: bridge